spring:
  profiles:
    active: dev
  thymeleaf:
    suffix: .html
    cache: true
    prefix: classpath:/templates/
    mode: HTML5
    encoding: utf-8
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql